# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cecad2304e3032209198fb8205ee4fee0554905b2fc838941c094930cafe4ff4364b3602668477ebb8a6f4b8d82746d5049ac2aded49658867077ec3c33c4c77

test:
  secret_key_base: d3e18a207db418374be7d2f01ab9ef6b08dd6361dfcb2cab88595038a07d2f18dbc29f24dcc92185bd0871d08a7a953d80bfe27b18c436446a1905084b5933ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
